<?php

/**
 * @file
 * Expires rows from the session table older than a configured time.
 */

/**
 * Implements hook_menu().
 *
 * @return array
 */
function session_expire_menu() {
  $items['admin/config/people/session_expire'] = array(
    'title' => 'Session expire',
    'description' => 'Settings for session expiry.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('session_expire_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'session_expire.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_cron().
 */
function session_expire_cron() {
  $timestamp = REQUEST_TIME - config_get('session_expire.settings', 'session_expire_age');

  $num_updated = db_delete('sessions')
    ->condition('timestamp', $timestamp, '<')
    ->execute();

  watchdog('cron', 'Number of sessions deleted: @num.', array('@num' => $num_updated), WATCHDOG_INFO);
}

